;-----------------------------------------------------------------------------------------
; 						SECCION DE MACROS PARA EL ENSAMBLADOR
;-----------------------------------------------------------------------------------------



;-----------------------------------------------------------------------------------------

;									ENTREGA_CPU

;DEVUELVE EL CPU AL PLANIFICADOR
ENTREGA_CPU	MACRO
	;COMO HAY UN CAMBIO DE CONTEXTO A LA VEZ, ESTA VARIABLE CONTIENE EL PUNTERO AL PC DE
	;LA ACTUAL TAREA EN EJECUCION
	BANKSEL PRINCIPIO_TAREA_ANTERIOR
	BANKISEL PRINCIPIO_TAREA_ANTERIOR
	MOVF PRINCIPIO_TAREA_ANTERIOR,W
	MOVWF FSR			;APUNTAMOS AL CONTEXTO ALTO DE LA TAREA
	MOVLW HIGH($+.9)	;ALMACENAMOS EN ACUMULADOR LA PAGINA ACTUAL
	MOVWF INDF			;Y LA GUARDAMOS EN CONTEXTO ALTO
	INCF FSR 			;APUNTAMOS AL CONTEXTO BAJO DE LA TAREA
	MOVLW LOW($+.6)		;ALMACENAMOS EL PUNTO DONDE REANUDARA LA EJECUCCION PARA ESTA PAGINA EN W
	MOVWF INDF			;Y LA GUARDAMOS EN CONTEXTO BAJO
	MOVLW HIGH(PLANIFICADOR) ;ACOMODAR LA PAGINA Y EL CONTADOR DE PROGRAMA PARA EJECUTAR
	MOVWF PCLATH			 ;EL PLANIFICADOR
	MOVLW LOW(PLANIFICADOR)
	MOVWF PCL
	ENDM

DEMORA MACRO TICKS


	TICK1A = TICKS / .255
	TICK1 = TICKS % .255

	TICK2A = TICK1A / .255
	TICK2 = TICK1A % .255

	TICK3A = TICK2A / .255
	TICK3 = TICK2A % .255

	TICK4A = TICK3A / .255
	TICK4 = TICK3A % .255

 	BCF INTCON,GIE
	BCF STATUS,IRP
	BCF STATUS,RP1
	BCF STATUS,RP0
	MOVF PRINCIPIO_TAREA_ANTERIOR,W
	MOVWF FSR			;APUNTAMOS AL CONTEXTO ALTO DE LA TAREA
	MOVLW HIGH($-.6);ALMACENAMOS EN ACUMULADOR LA PAGINA ACTUAL
	MOVWF INDF			;Y LA GUARDAMOS EN CONTEXTO ALTO
	INCF FSR 			;APUNTAMOS AL CONTEXTO BAJO DE LA TAREA
	MOVLW LOW($-.9);ALMACENAMOS EL PUNTO DONDE REANUDARA LA EJECUCCION PARA ESTA PAGINA EN W
	MOVWF INDF			;Y LA GUARDAMOS EN CONTEXTO BAJO

	BANKSEL TICK_8BIT_TMP


	MOVLW TICK1
	MOVWF TICK_8BIT_TMP
	
	MOVLW TICK2
	MOVWF TICK_16BIT_TMP

	MOVLW TICK3
	MOVWF TICK_24BIT_TMP

	MOVLW TICK4
	MOVWF TICK_32BIT_TMP


	CALL TEMPORIZADOR
	BSF INTCON,GIE
	ENTREGA_CPU	
	
	ENDM

CUENTA_TIEMPO MACRO TICKS,LLAVE

	TICK1A = TICKS / .255
	TICK1 = TICKS % .255

	TICK2A = TICK1A / .255
	TICK2 = TICK1A % .255

	TICK3A = TICK2A / .255
	TICK3 = TICK2A % .255

	TICK4A = TICK3A / .255
	TICK4 = TICK3A % .255
	;BCF INTCON,GIE
	NOP
	BCF STATUS,IRP
	BCF STATUS,RP1
	BCF STATUS,RP0
	MOVF PRINCIPIO_TAREA_ANTERIOR,W
	MOVWF FSR			;APUNTAMOS AL CONTEXTO ALTO DE LA TAREA
	MOVLW HIGH($-.6);ALMACENAMOS EN ACUMULADOR LA PAGINA ACTUAL
	MOVWF INDF			;Y LA GUARDAMOS EN CONTEXTO ALTO
	INCF FSR 			;APUNTAMOS AL CONTEXTO BAJO DE LA TAREA
	MOVLW LOW($-.9);ALMACENAMOS EL PUNTO DONDE REANUDARA LA EJECUCCION PARA ESTA PAGINA EN W
	MOVWF INDF			;Y LA GUARDAMOS EN CONTEXTO BAJO

	

	BANKSEL B_TEMPORIZADOR

	
	MOVLW LLAVE
	MOVWF GENERAL_TEMP
	
	
	MOVLW TICK1
	MOVWF TICK_8BIT_TMP
	
	MOVLW TICK2
	MOVWF TICK_16BIT_TMP

	MOVLW TICK3
	MOVWF TICK_24BIT_TMP

	MOVLW TICK4
	MOVWF TICK_32BIT_TMP

	CALL TEMPORIZADOR_NB
	;BSF INTCON,GIE
	ENDM

CHEQUEA_TEMP MACRO LLAVE, ETIQUETA
	;BCF INTCON,GIE
	BANKSEL B_TEMPORIZADOR
	BANKISEL B_TEMPORIZADOR
	MOVLW LLAVE
	MOVWF GENERAL_TEMP
	CALL CHEQUEAR_TEMPORIZADOR
	XORLW TEMPORIZADOR_NB_EXPIRO
	;BSF INTCON,GIE
	BTFSS STATUS,Z
	GOTO ETIQUETA
	ENDM

;-----------------------------------------------------------------------------------------
; 	FIN		FIN		FIN		FIN SECCION DE MACROS FIN	FIN		FIN	
;-----------------------------------------------------------------------------------------
